pod 'ECSlidingViewController', '~> 0.10.0'
pod 'AFNetworking', '~> 1.3.0'
pod 'MDCParallaxView', '~> 0.1.4'
pod 'sundown', '~> 0.1.0'
pod 'DTCoreText', '~> 1.6.9'
pod 'MagicalRecord', '~> 2.0'
pod 'ODRefreshControl', '~> 1.1.0'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.0.2'